### ISSUE TITLE
Never used variable 'tmp_slice'

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [XiaoMi/pegasus-rocksdb#24]
https://github.com/XiaoMi/pegasus-rocksdb/blob/dc91f8a9567b65cea9cc7d1cc792ddd764141638/table/plain_table_reader.cc#L718

advice: delete the variable which is never used

**Comment by acelyc111** [comment]
Thanks! It's an issue indeed. However, this repo is forked from https://github.com/facebook/rocksdb, we just modified some Pegasus related code.
